### ISSUE TITLE
ORDERSCAR AND MR. EXPLOSION MAN SHOULD WORK WITH CAPS LOCK

### ISSUE THREAD

**Issue by rtcrotty** [Roadcrosser/roadcrosser.github.io#1]
ALSO I'M NOT SURE WHAT LOWERCASE LETTERS ARE SEND HELP

**Comment by Roadcrosser** [comment]
[Implemented](https://github.com/Roadcrosser/roadcrosser.github.io/commit/1dbf050e0e739f433a6cc8f7ab9d725d1a54dea7).

**Comment by Roadcrosser** [comment]
This issue was moved to Roadcrosser/Unumanus#2
