### ISSUE TITLE
dont invalid request me

### ISSUE THREAD

**Issue by coretheguy** [Roadcrosser/roadcrosser.github.io#3]
# yer gonna add that <st>

**Comment by Roadcrosser** [comment]
invalid request.

**Comment by coretheguy** [comment]
![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13134566/c8220352-d5bc-11e5-8c92-7687a443c930.png)

**Comment by Roadcrosser** [comment]
This issue was moved to Roadcrosser/Unumanus#4
