### ISSUE TITLE
WHAT DOES INVALID REQUEST EVNE EMAN

### ISSUE THREAD

**Issue by coretheguy** [Roadcrosser/roadcrosser.github.io#4]
i requested a star command, which randomizes the orng2 selections, picks one, and appends it into the text

_is this good for you yet??????????????_ 
![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13134597/116fb45a-d5bd-11e5-9820-d12618ca827c.png)

**Comment by Roadcrosser** [comment]
[Implemented](https://github.com/Roadcrosser/roadcrosser.github.io/commit/928a382a73b957907c81c7633926b50bdf46fdd0).

**Comment by Roadcrosser** [comment]
This issue was moved to Roadcrosser/Unumanus#5
