### ISSUE TITLE
add a <csans> script

### ISSUE THREAD

**Issue by coretheguy** [Roadcrosser/roadcrosser.github.io#5]
does a random/special name for my name/normal screenname. (includes "corns," "field of corn", etc.) and appends it

**Comment by Roadcrosser** [comment]
**Outside the scope of this project. Closed.**

**Comment by coresans** [comment]
![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png) ![screenshot_78](https://cloud.githubusercontent.com/assets/17308471/13167689/658b88b6-d68a-11e5-9704-703fad1608d6.png)

**Comment by Roadcrosser** [comment]
This issue was moved to Roadcrosser/Unumanus#6
